### ISSUE TITLE
check

### ISSUE THREAD

**Issue by DThuo** [o-william-white/skim2mt#30]
getting this error:
(snakemake) PS C:\Users\xxxxxx\skim2mt> snakemake --cores 2 --use-conda --config user_email=xxxx0@gmail.com
IndentationError in file C:\Users\Njoroges\skim2mt\workflow\Snakefile, line 32:
expected an indented block after 'if' statement on line 83 (Snakefile, line 32)

I have tried tweaking the source code, but still getting the error.

**Comment by o-william-white** [comment]
Hi @DThuo, 

Thanks for highlighting this issue. I re-ran the test data on the main branch and I am unable to replicate the error. I wonder if this is due to different in snakemake versions? See https://github.com/snakemake/snakemake/issues/2765 

I am using using snakemake verison 8.4.12. What version are you working with? 

Cheers
Ollie

**Comment by o-william-white** [comment]
Hi @DThuo, happy to work on this if you can give me more details on replicating the issue. Will close for now. 

Cheers
Ollie
